#!/bin/bash

# Run the Python scripts
python ./scripts/bluesky.py
python ./scripts/linkding.py
python ./scripts/gts-md.py

# Prompt to rebuild Hugo
read -p "Do you want to proceed and rebuild the site? (y/n): " response
if [[ "$response" != "y" ]]; then
  echo "Exiting the script."
  exit 1
fi

# Build the Hugo site in staging mode
echo -e "\n\nSTAGING:\n"
hugo -e staging
echo -e "\n\nPRODUCTION:\n"
hugo

# Check git status and prompt commit changes
git status
if [[ -z "$(git status --porcelain)" ]]; then
  echo "No changes to commit. Exiting the script."
  exit 0
fi

read -p "Do you want to proceed with staging, committing, and pushing changes? (y/n): " git_response
if [[ "$git_response" != "y" ]]; then
  echo "Exiting the script."
  exit 1
fi

# Stage all changes
git add .

# Commit the changes with a message
git commit -m "updated asides"

# Push the changes to the remote repository
git push
